
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16.18.0

# Defines our working directory in container
WORKDIR /usr/src/app

RUN install_packages wget git patch

# Copies the package.json first for better cache on later pushes
COPY package.json package.json

# This install npm dependencies on the resin.io build server,
# making sure to clean up the artifacts it creates in order to reduce the image size.
RUN JOBS=MAX npm install --production

# This will copy all files in our root to the working  directory in the container
COPY . ./

# Run when container starts up on the device
#
# COMMENT THE FOLLOWING CMD TO RUN THE APP IN THIS CONTAINER.
#
CMD ["npm", "start"]